@isTest
public class leadConversionController_Test {
    @IsTest
    static void test_leadConversion() {
        Lead ld = new Lead(LastName='leadLN', Company='TestLeadConversion' );
        insert ld;
        
//convertLead (id leadRecId, boolean isNewAcct, boolean isNewContact, boolean isNewOpp, boolean noCreatedOpp,id acctRecId, id contactRecId, id oppRecId)

        
    }    
                                  
}