public class SageApiAddCommUserActivityRequest extends SageApiActivityRequestBase {
    public String AccountId;
    public String ContactId;
    public String firstName;
    public String lastName;
    public String email;
    public String phone;
    public String address1;
    public String address2;
    public String city;
    //public String county;
    public String postalCode;
    public String state;
    public String countryCode;
    public String communityType;
    public String communityRole;//Sage One User, Sage One Trial, Customer Account Administrator
    public string identityType;
    public string identityId;
}