public class SageApiProcessLocks {
    public final static string None = 'None';
    public final static string Validation = 'Validation';
    public final static string Lead = 'Lead';
    public final static string LeadConvert = 'LeadConvert';
    public final static string User = 'User';
    public final static string Quote = 'Quote';
    public final static string PayNow = 'PayNow';
    public final static string Subscription = 'Subscription';
    public final static string Entitlement = 'Entitlement';
    public final static string Restarting = 'Restarting';
}