/*-------------------------------------------------------------
    Author:         Lakshman
    Date :          08/18/2017
    Company:       Docmation LLC
    Description:   Test Class for SPPReferralOrderDetailWrapper
    Inputs:        None
    History
    <Date>            <Authors Name>                <Brief Description of Change>
  
  ------------------------------------------------------------*/

@isTest
public class SPPReferralOrderDetailWrapperTest {


    Static TestMethod void TestOrderDetail(){
        Id test;
        SPPReferralOrderDetailWrapper noParam = new SPPReferralOrderDetailWrapper();
        SPPReferralOrderDetailWrapper obj = new SPPReferralOrderDetailWrapper('Test1','Test1','Test1','Test1','Test1',1,'Test1','Test1','0Nt7E0000004FIJ','Test1');
    }

}