/*-------------------------------------------------------------
    Author:         Lakshman
    Date :          08/18/2017
    Company:       Docmation LLC
    Description:   Test Class for SPPScheduleDocuSignBulkWrapper
    Inputs:        None
    History
    <Date>            <Authors Name>                <Brief Description of Change>
  
  ------------------------------------------------------------*/
@isTest
private class SPPScheduleDocuSignBulkWrapperTest
{
    @isTest
    static void itShould()
    {
        SPPScheduleDocuSignBulkWrapper wr = new SPPScheduleDocuSignBulkWrapper();

    }
}