/**********************************************************************************************************************     
    Name        : TestUtilsCreateStandardObjects  
    Date        : 09/18/2017
    Desctiption : Utility class creates objects for test classes.
    Author      : 
    Modified    : 
    Comment     :  

THESE METHODS INCLUDE RECORD CREATION/UPDATES DML IS COMPLETE AND THE RETURNED OBJECT IS ALREADY IN THE DATABASE

***********************************************************************************************************************/
@isTest(SeeAllData=false) 
public class TestUtilsCreateCCObjects {}