/**
* @author Prasanti Avula, Docmation
* @creationDate August 17, 2017
*
* @description REST API to Create A Cart in CC. This is used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 17, 2017 - Prasanti Avula
*       Created the initial version to create a cart through a REST API.
* ------------------------------------------------------------------------------------------------------------
*/

//@RestResource(urlMapping='/TetrisCartCreationService')
global with sharing class TetrisCartCreationService {}