/**
* @author Junaid Mohammed, Docmation
* @creationDate November 1, 2017
*
* @description 		Helper class to generate the Payload for SLCS Subscription 
*					based on the Products selected in the cart
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - November 1, 2017 - Junaid Mohammed
*       						Intitial Version
* ------------------------------------------------------------------------------------------------------------
*/
global class TetrisProductProvisionManager {}