global class TetrisContactModel {
	global String firstName{get; set;}
    global String lastName{get; set;}
    global String email{get; set;}
    global String phone{get; set;}
    global String contactId{get; set;}
    global String streetAddress{get; set;}
    global String city{get; set;}
    global String state{get; set;}
    global String country{get; set;}
    global String postalCode{get; set;}
    global Boolean emailOptout{get; set;}
    global Datetime optInOutTime{get; set;}
    // @Rishu Garg Docmation (EADAPPI-541)
    global String industry{get; set;}
}