/**
* @author Prasanti Avula, Docmation
* @creationDate August 1, 2017
*
* @description Helper class supporting methods for all Product Management functions in CloudCraze. These functions
*			   are used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 1, 2017 - Prasanti Avula
*       Created the initial version to support helper methods for CloudCraze (Get Products By Sku, Get All Products, Get Tiered Pricing Info 
*       etc.)
* ------------------------------------------------------------------------------------------------------------
*/

global class TetrisProductManager {}