/**
* @author Prasanti Avula, Docmation
* @creationDate August 25, 2017
*
* @description REST API to create Account,Contact,Lead and Opportunity In Salesforce which is invoked by MuleSoft. This API 
*			   is used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 25, 2017 - Prasanti Avula
*       Created the initial version to create Account,Contact,Lead and Opportunity in Salesforce through a REST API.
* ------------------------------------------------------------------------------------------------------------
*/

//@RestResource(urlMapping='/TetrisAccountService')
global with sharing class TetrisAccountService {}