global class TetrisZuoraRequestModel {
    global String sku {get;set;}
    global String contractEffectiveDate {get;set;}
    global String subscriptionId {get;set;}
    global String quantity {get;set;}
    global String discountType {get;set;}
    global String billingFrequency {get;set;}
    global String discount {get;set;}
    global String OneTimeOrRecurring {get;set;}
    global Boolean tieredPricing {get;set;}
    global String bundleName {get;set;}
    global String bundleDesc {get;set;}
    global String bundleInstance {get;set;}
    global String uom {get;set;}
    global String couponCode {get;set;}
    global String couponLength {get;set;}
    global String couponPeriod {get;set;}
}