/**
* @author Prasanti Avula, Docmation
* @creationDate August 15, 2017
*
* @description Helper class supporting methods for all Cart Management functions in CloudCraze. These functions
*              are used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 15, 2017 - Prasanti Avula
*       Created the initial version to support helper methods for CloudCraze (Create Cart, Add to Cart, List 
*       Cart etc.)
* ------------------------------------------------------------------------------------------------------------
*/
global without sharing class TetrisCartManager {}