/**
* @author Prasanti Avula, Docmation
* @creationDate August 21, 2017
*
* @description REST API to fetch Cart Related Info. This is used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 21, 2017 - Prasanti Avula
*       Created the initial version to fetch Cart Related Info through a REST API.
* ------------------------------------------------------------------------------------------------------------
*/
//@RestResource(urlMapping='/TetrisCartListService')
global with sharing class TetrisCartListService {}