/**
* @author Vikram Datla, Docmation
* @creationDate August 1, 2017
*
* @description Helper class for performing common Tetris Cart operations. These functions
*			   are used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 1, 2017 - Vikram Datla
*       Created the initial version to support common Tetris Cart operations.
* ------------------------------------------------------------------------------------------------------------
*/
// Helper class for performing common Tetris Cart operations
public class TetrisCartHelper {}