/**
* @author Prasanti Avula, Docmation
* @creationDate August 12, 2017
*
* @description Wrapper Class with Account Related info. This is used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 12, 2017 - Prasanti Avula
*       Created the initial version of Wrapper Class.
* ------------------------------------------------------------------------------------------------------------
*/
global class TetrisAccountResultModel extends TetrisBaseModel {

    global String accountId;
	global String contactId;
    global String leadId;
   	global String opportunityId;
   	global String zuoraAccountId;
   	global String cartId;
    global String communicationProfileId;
    global String invoiceTemplateId;
    global String paymentGateway;
    global String vatNumber;
    global Boolean taxExempt;

    global String transactionType;

}