/**
* @author Prasanti Avula, Docmation
* @creationDate August 21, 2017
*
* @description REST API to Add Product To CC Cart Object. This is used in TETRIS R2.
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 21, 2017 - Prasanti Avula
*       Created the initial version to add product to Cart through a REST API.
* ------------------------------------------------------------------------------------------------------------
*/
//@RestResource(urlMapping='/TetrisAddToCartService')
global with sharing class TetrisAddToCartService {}