global class TetrisBillingProductChargeModel {
    
    global String originalChargeId {get; set;}
    global String productRatePlanChargeId {get; set;}
    global String chargeNumber {get; set;}
    global String name {get; set;}
    global String chargeType {get; set;}
    global String model {get; set;}
    global Decimal price {get; set;}
    global String pricingSummary {get; set;}
    global String billingCurrency {get; set;}
    global String applyDiscountTo {get; set;}
    global String billingDay {get; set;}
    global String billingPeriod {get; set;}
    global Date effectiveStartDate {get; set;}
    global Date effectiveEndDate {get; set;}
    global String endDateCondition {get; set;}
    global String uptoPeriodsType {get; set;}
    global Integer upToPeriods {get; set;}
    global String description {get; set;}
    global String productBundleName {get; set;}
    global String productBundleInstanceId {get; set;}
    global String productBundleDescription {get; set;}
    global String productDescription {get; set;}
    global String productName {get; set;}
    global String productSKU {get; set;}
    global Decimal quantity {get; set;}
    global String ratePlanName {get; set;}
    global String ratePlanDescription {get; set;}
    global Double totalContractValue {get; set;}
    
}