/**
* @author Prasanti Avula, Docmation
* @creationDate March 20, 2018
*
* @description REST API to Create, Add Product, Apply Coupon and display Tetris Cart . 
*
* Modification Log
* ------------------------------------------------------------------------------------------------------------
* 1.0 - August 21, 2017 - Prasanti Avula
*       Created the initial version to add product to Cart through a REST API.
* ------------------------------------------------------------------------------------------------------------
*/
//@RestResource(urlMapping='/TetrisAddProductToCartService')
global with sharing class TetrisAddProductToCartService {}